name: Auto Checkin Job

on:
  schedule:
    # 每天早上 6 点北京时间（UTC+8）运行
    - cron: "0 22 * * *" # UTC 时间 22:00 对应北京时间 6:00
  workflow_dispatch: # 允许手动触发

jobs:
  auto-sign:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 环境

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # 指定 Node.js 版本
          cache: "npm"

      # 3. 安装依赖
      - name: Install dependencies
        run: npm ci

      # 4. 运行TypeScript脚本并捕获输出
      - name: Run auto checkin script
        id: run_script # 给步骤命名，方便后续引用输出
        continue-on-error: true
        env:
          TOKEN: ${{ secrets.TOKEN }}
          DEBUG: ${{ secrets.DEBUG }}
          BARK_DEVICE_KEY: ${{ secrets.BARK_DEVICE_KEY }}
          BARK_SERVER_URL: ${{ secrets.BARK_SERVER_URL }}
          SERVER3_SEND_KEY: ${{ secrets.SERVER3_SEND_KEY }} # ServerChan3
        run: |
          npm run dev
